require 'sinatra'
require 'active_record'
require_relative 'config.rb'
require_relative 'models/autor.rb'
require_relative 'models/livro.rb'
require_relative 'models/editora.rb'
require_relative 'models/usuario.rb'